# Generated by Django 6.0.3 on 2026-04-05 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Disponible pour échanger sur WhatsApp'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Professeur/Expert vérifié'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Numéro WhatsApp avec indicatif (ex: +225XXXXXXXXXX)', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Apprenant'), ('teacher', 'Professeur'), ('expert', 'Expert')], default='student', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='speciality',
            field=models.CharField(blank=True, help_text='Spécialité (pour professeurs/experts)', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='years_experience',
            field=models.IntegerField(default=0, help_text="Années d'expérience"),
        ),
    ]
