# Generated by Django 6.0.3 on 2026-05-28 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingx', '0002_userprofile_is_available_userprofile_is_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CultureContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('tradition', 'Tradition'), ('history', 'Histoire'), ('custom', 'Coutume'), ('celebration', 'Célébration')], max_length=20)),
                ('description', models.TextField()),
                ('detailed_content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/culture/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Culture Contents',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Proverb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proverb_baule', models.TextField()),
                ('proverb_french', models.TextField()),
                ('meaning', models.TextField(help_text='Explication du proverbe')),
                ('usage_context', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, help_text='Ex: Sagesse, Famille, Travail', max_length=100)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/proverbs/')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserCultureView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('culture_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lingx.culturecontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culture_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'culture_content')},
            },
        ),
    ]
