# Generated by Django 6.0.3 on 2026-05-28 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingx', '0003_culturecontent_proverb_usercultureview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaouleName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_baule', models.CharField(max_length=100, unique=True)),
                ('meaning_french', models.TextField()),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('U', 'Unisexe')], default='U', max_length=1)),
                ('origin', models.CharField(blank=True, help_text='Origine ou histoire du prénom', max_length=200)),
                ('cultural_significance', models.TextField(blank=True, help_text='Signification culturelle')),
                ('similar_names', models.TextField(blank=True, help_text='Prénoms similaires ou variantes')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/names/')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name_baule'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('story_type', models.CharField(choices=[('legend', 'Légende'), ('tale', 'Conte'), ('history', 'Histoire'), ('fable', 'Fable')], default='tale', max_length=20)),
                ('description', models.TextField()),
                ('full_text', models.TextField()),
                ('baule_text', models.TextField(blank=True, help_text='Texte original en Baoulé si disponible')),
                ('moral_lesson', models.TextField(blank=True, help_text='Leçon morale ou enseignement')),
                ('characters', models.TextField(blank=True, help_text='Personnages principaux (séparés par des virgules)')),
                ('difficulty', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé')], default='debutant', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/stories/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/stories/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryVocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_baule', models.CharField(max_length=100)),
                ('word_french', models.CharField(max_length=100)),
                ('pronunciation', models.CharField(blank=True, max_length=150)),
                ('context_sentence', models.TextField(blank=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabularies', to='lingx.story')),
            ],
            options={
                'verbose_name_plural': 'Story Vocabularies',
            },
        ),
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_baule', models.CharField(max_length=100, unique=True)),
                ('word_french', models.CharField(max_length=100)),
                ('pronunciation', models.CharField(blank=True, max_length=150)),
                ('part_of_speech', models.CharField(blank=True, help_text='Nom, Verbe, Adjectif, etc.', max_length=50)),
                ('definition', models.TextField()),
                ('example_sentence_baule', models.TextField(blank=True)),
                ('example_sentence_french', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/dictionary/')),
                ('synonyms', models.TextField(blank=True, help_text='Synonymes (séparés par des virgules)')),
                ('antonyms', models.TextField(blank=True, help_text='Antonymes (séparés par des virgules)')),
                ('usage_context', models.CharField(blank=True, max_length=200)),
                ('is_common', models.BooleanField(default=False)),
                ('is_formal', models.BooleanField(default=False)),
                ('search_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Dictionary Entries',
                'ordering': ['word_baule'],
                'indexes': [models.Index(fields=['word_baule'], name='lingx_dicti_word_ba_510449_idx'), models.Index(fields=['is_common'], name='lingx_dicti_is_comm_73ead0_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserStoryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lingx.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'unique_together': {('user', 'story')},
            },
        ),
    ]
