# Generated by Django 6.0.3 on 2026-05-29 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingx', '0004_baoulename_story_storyvocabulary_dictionaryentry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('learning', '📚 Apprentissage'), ('completion', '✅ Complétude'), ('consistency', '🔥 Constance'), ('speed', '⚡ Rapidité'), ('accuracy', '🎯 Précision'), ('social', '👥 Social'), ('collector', '🏺 Collecteur')], max_length=20)),
                ('icon', models.CharField(default='⭐', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievements/')),
                ('condition_type', models.CharField(max_length=50)),
                ('condition_value', models.IntegerField()),
                ('points_reward', models.IntegerField(default=100)),
                ('rarity', models.CharField(choices=[('common', 'Courant'), ('rare', 'Rare'), ('epic', 'Épique'), ('legendary', 'Légendaire')], default='common', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('streak_started', models.DateField(blank=True, null=True)),
                ('total_activities', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_date', models.DateField()),
                ('points', models.IntegerField(default=10)),
                ('bonus_multiplier', models.FloatField(default=1.0, help_text='Multiplicateur basé sur le streak')),
                ('is_claimed', models.BooleanField(default=False)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(default='Connexion quotidienne', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reward_date'],
                'unique_together': {('user', 'reward_date')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('times_completed', models.IntegerField(default=1)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lingx.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('achievement', '🏆 Succès'), ('badge', '🎖️ Badge'), ('milestone', '⭐ Jalon'), ('streak', '🔥 Série'), ('level_up', '⬆️ Niveau'), ('reward', '🎁 Récompense'), ('challenge', '🎯 Défi'), ('leaderboard', '📊 Classement')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('icon', models.CharField(default='ℹ️', max_length=50)),
                ('points_awarded', models.IntegerField(default=0)),
                ('is_read', models.BooleanField(default=False)),
                ('action_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='lingx_usern_user_id_c8c001_idx'), models.Index(fields=['is_read'], name='lingx_usern_is_read_d63255_idx')],
            },
        ),
        migrations.CreateModel(
            name='VocabularyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_rating', models.CharField(choices=[('easy', '✓ Facile'), ('medium', '≈ Normal'), ('hard', '✗ Difficile')], max_length=10)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('review_count', models.IntegerField(default=0)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('retention_score', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_reviews', to=settings.AUTH_USER_MODEL)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lingx.vocabulary')),
            ],
            options={
                'ordering': ['user', '-reviewed_at'],
                'indexes': [models.Index(fields=['user', 'vocabulary'], name='lingx_vocab_user_id_0d406a_idx'), models.Index(fields=['next_review_date'], name='lingx_vocab_next_re_c51db8_idx')],
            },
        ),
    ]
