# Generated by Django 6.0.3 on 2026-05-30 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingx', '0005_achievement_userstreak_dailyreward_userachievement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='minigame',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minigames', to='lingx.lesson'),
        ),
    ]
