# Generated by Django 6.0.3 on 2026-05-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingx', '0006_minigame_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='number',
            field=models.IntegerField(default=0, help_text='Numéro de la leçon (1-22) pour déblocage par niveau'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='number',
            field=models.IntegerField(default=0, help_text='Numéro du test (1-22) pour déblocage par niveau'),
        ),
    ]
